### ISSUE TITLE
Permission de partager du code 

### ISSUE THREAD

**Issue by gabinacode** [ericsprepa/Maths-MP2I-Guy-Mollet#1]
Bonsoir, 

En tant que futur élève de la prépa mp2i à Guy Mollet, serait-il possible d'avoir la possibilité de soumettre du code (principalement du css, et une modification de l'architecture html) afin de rendre le site plus agréable visuellement ?

Cordialement,
Gabin

**Comment by ericsprepa** [comment]
Bonjour, merci pour cette proposition mais cette page a été créée dans l'attente de savoir quel site et support sera privilégié à la rentrée pour le partage des documents et causée également par la fin du site de partage de document avec ma précédente prépa que j'utilisais sur un autre serveur. C'est la raison pour laquelle je n'ai mis que le document de travail pour l'instant.
Cordialement
E.Swiadek

**Comment by gabinacode** [comment]
Bonjour M. Swiadek,

Merci pour votre réponse rapide. Je comprends la situation actuelle. Si jamais vous décidez de continuer à utiliser cette page pour partager des documents, n'hésitez pas à me faire savoir si vous avez besoin d'aide pour l'amélioration du site. Je serais ravi de contribuer de cette façon.

En attendant, bonnes vacances à vous !

Cordialement,
G.Bruniaux
